language: python

python:
  - 2.7

before_install:
    - pip install python-coveralls
    - pip install nose

script:
    - cd ray-core
    - pip install -r requirements.txt
    - nosetests --tests=tests --with-coverage --cover-package=ray
    -cd ..

    - pip install . # install ray-core
    - cd ray-appengine
    - pip install . # install ray-appengin
    - nosetests --tests=tests --with-coverage --cover-package=ray_appengine
    # - cd ..
    # - cd ray-sqlalchemy/
    # - pip install .
    #
    # - cd tests/
    # - ./run_tests.sh

after_success:
  - coveralls --config_file=.coveragerc

notifications:
    email:
        recipients:
            - felipevolpone@gmail.com
        on_success: change
        on_failure: always
