language: python

python:
  - 2.7

before_install:
    - pip install python-coveralls
    - pip install nose

    - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.38.zip
    - unzip -q google_appengine_1.9.38.zip
    - pwd
    - ls -la
    # - mv google_appengine /opt/
    - export PATH=$PATH:/opt/google_appengine/
    - export PYTHONPATH="$PYTHONPATH:/opt/google_appengine/"

script:
    - cd ray-core
    - pip install . # install ray-core
    - pip install -r requirements.txt
    - nosetests --tests=tests --with-coverage --cover-package=ray

    - cd ..
    - cd ray-appengine
    - pip install . # install ray-appengine
    - nosetests --tests=tests --with-coverage --cover-package=ray_appengine

after_success:
  - coveralls --config_file=.coveragerc

notifications:
    email:
        recipients:
            - felipevolpone@gmail.com
        on_success: change
        on_failure: always
