language: python

python:
  - 2.7

before_install:
    - sudo pip install coveralls

script:
  - pip install -r onhands-core/requirements.txt
  - cd onhands-core
  - pip freeze
  - py.test -v tests/ --cov onhands

after_success:
  - coveralls

notifications:
    email:
        recipients:
            - felipevolpone@gmail.com
        on_success: change
        on_failure: always
