language: python

python:
  - 2.7

before_install:
  - sudo pip install -r requirements.txt
  - sudo pip install coveralls

script:
  - py.test -v tests/ --cov onhands/

after_success:
  - coveralls

notifications:
    email:
        recipients:
            - felipevolpone@gmail.com
        on_success: change
        on_failure: always
