language: python

python:
  - 2.7

before_install:
    - pip install python-coveralls
    - pip install nose

script:
    - cd ray-core
    - pip install . # install ray-core
    - pip install -r requirements.txt
    - nosetests --tests=tests --with-coverage --cover-package=ray
    # - cd ..

    # - ls -la
    # - cd ray-appengine
    # - pip install . # install ray-appengine
    # - nosetests --tests=tests --with-coverage --cover-package=ray_appengine

after_success:
  - coveralls --config_file=.coveragerc

notifications:
    email:
        recipients:
            - felipevolpone@gmail.com
        on_success: change
        on_failure: always
