language: python

python:
  - 2.7

before_install:
    - sudo pip install coveralls

script:
  # onhands-core build
  - pip install -r onhands-core/requirements.txt
  - cd onhands-core
  - pip install --editable .
  - py.test -v tests/ --cov onhands

  # onhands-sqlalchemy build
  - cd ../onhands-sqlalchemy/
  - pip install --editable .
  - pip install requests
  - cd tests/
  - onhands up --wsgifile app.py &
  - sleep 2
  - py.test test_integrated.py


after_success:
  - coveralls

notifications:
    email:
        recipients:
            - felipevolpone@gmail.com
        on_success: change
        on_failure: always
