language: python

python:
  - 2.7

before_install:
    - sudo pip install coveralls
    - sudo pip install -r onhands-core/requirements.txt

script:
  - cd onhands-core
  # - py.test -v tests/ --cov onhands/
  - sudo pip install webapp2 --upgrade
  - py.test -v tests/

after_success:
  - coveralls

notifications:
    email:
        recipients:
            - felipevolpone@gmail.com
        on_success: change
        on_failure: always
