language: python

python:
  - 2.7

before_install:
    - pip install python-coveralls
    - pip install nose

script:
    - cd ray-core
    - pip install -r requirements.txt
    #- py.test tests/ --cov ray/
    - nosetests --tests=tests --with-coverage --cover-package=ray
    # - pip install --editable .
    # - cd ..

    # - cd ray-sqlalchemy/
    # - pip install --editable .
    # - pip install requests
    # - cd tests/
    # - ray up --wsgifile app.py &
    # - sleep 2
    # - py.test test_integrated.py

    # - cd ../../ray-core
    # - py.test -v tests/ --cov ray


after_success:
  - coveralls --config_file=ray-core/.coveragerc

notifications:
    email:
        recipients:
            - felipevolpone@gmail.com
        on_success: change
        on_failure: always
